//! This file is auto-generated by zpm-update and *should*
//! not be changed. This file can be checked into your VCS
//! and is able to work standalone.
const std = @import("std");

pub const pkgs = struct {
    pub const @"parser-toolkit" = std.build.Pkg{
        .name = "parser-toolkit",
        .source = .{ .path = "vendor/parser-toolkit/src/main.zig" },
    };
};
